inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-rails-suite: rubocop.yml

# Specify your Ruby version
AllCops:
  TargetRubyVersion: 3.4

# Custom
Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'config/initializers/simple_form.rb'

Rails/EnumHash:
  Enabled: false